"""Public Discovery and Marketplace Integration (v2.7.0).

Discovery adds reachability.
Discovery does not add trust.

NON-NEGOTIABLE RULES:
    Marketplace listing is not certification.
    Discovery index signature is not package trust.
    Registry reachability is not registry eligibility.
    Popularity is not reputation.
    Reputation is not trust.

Discovery is a proposal layer. Discovered registries become normal
FederatedRegistryConfig entries only after operator/profile approval.
"""

from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


DISCOVERY_VERSION = "v1"

# Safety limits
MAX_INDEX_SIZE_BYTES = 10 * 1024 * 1024  # 10 MB
MAX_REGISTRIES_PER_INDEX = 500
MAX_PACKAGES_PER_INDEX = 10000


class DiscoveryError(Exception):
    """Raised when discovery index is corrupt, stale, or oversized."""


class MarketplacePolicyDenial(Exception):
    """Raised when organization policy denies a marketplace operation."""


# ── Marketplace Registry Listing ─────────────────────────────────────────────

@dataclass
class MarketplaceRegistryListing:
    """A single registry listing from a discovery index.

    This is informational only. It does NOT confer trust, eligibility,
    or certification. It proposes a registry for operator consideration.
    """
    registry_id: str
    base_url: str
    display_name: str = ""
    description: str = ""
    categories: list[str] = field(default_factory=list)
    claimed_publishers: list[str] = field(default_factory=list)
    claimed_packages: list[str] = field(default_factory=list)
    reputation_hint: str = ""  # informational, never authoritative
    discovery_metadata_digest: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "registry_id": self.registry_id,
            "base_url": self.base_url,
            "display_name": self.display_name,
            "description": self.description,
            "categories": self.categories,
            "claimed_publishers": self.claimed_publishers,
            "claimed_packages": self.claimed_packages,
            "reputation_hint": self.reputation_hint,
            "discovery_metadata_digest": self.discovery_metadata_digest,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> MarketplaceRegistryListing:
        return cls(
            registry_id=d["registry_id"],
            base_url=d["base_url"],
            display_name=d.get("display_name", ""),
            description=d.get("description", ""),
            categories=d.get("categories", []),
            claimed_publishers=d.get("claimed_publishers", []),
            claimed_packages=d.get("claimed_packages", []),
            reputation_hint=d.get("reputation_hint", ""),
            discovery_metadata_digest=d.get("discovery_metadata_digest", ""),
        )

    def to_federation_config(self) -> Any:
        """Convert to a FederatedRegistryConfig for proposal (not auto-add).

        Claimed packages and publishers are informational only.
        They do NOT become allowlist restrictions.
        """
        from nodechain.sdk.federation import FederatedRegistryConfig
        return FederatedRegistryConfig(
            registry_id=self.registry_id,
            base_url=self.base_url,
            trust_level="remote_untrusted",  # always untrusted from discovery
            allowed_publishers=[],  # empty = all (claims are informational)
            allowed_packages=[],  # empty = all (claims are informational)
            priority=100,  # default lowest priority
            enabled=False,  # disabled until explicitly approved
        )


# ── Public Discovery Index ───────────────────────────────────────────────────

@dataclass
class PublicDiscoveryIndex:
    """A discovery index from a public source.

    Attributes:
        index_id: Unique identifier for this index
        source_url: URL where the index was fetched from
        generated_at: When the index was generated by its publisher
        registries: List of MarketplaceRegistryListing entries
        publishers: Known publisher fingerprints in this index
        packages: Known package IDs in this index
        index_digest: SHA-256 of the index content
        signature: Optional RSA-PSS-SHA256 signature of the index
        signer_fingerprint: Optional fingerprint of the signer
    """
    index_id: str
    source_url: str
    generated_at: str
    registries: list[MarketplaceRegistryListing] = field(default_factory=list)
    publishers: list[str] = field(default_factory=list)
    packages: list[str] = field(default_factory=list)
    index_digest: str = ""
    signature: str = ""
    signer_fingerprint: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "index_id": self.index_id,
            "source_url": self.source_url,
            "generated_at": self.generated_at,
            "registries": [r.to_dict() for r in self.registries],
            "publishers": self.publishers,
            "packages": self.packages,
            "index_digest": self.index_digest,
            "signature": self.signature,
            "signer_fingerprint": self.signer_fingerprint,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> PublicDiscoveryIndex:
        return cls(
            index_id=d["index_id"],
            source_url=d.get("source_url", ""),
            generated_at=d.get("generated_at", ""),
            registries=[MarketplaceRegistryListing.from_dict(r) for r in d.get("registries", [])],
            publishers=d.get("publishers", []),
            packages=d.get("packages", []),
            index_digest=d.get("index_digest", ""),
            signature=d.get("signature", ""),
            signer_fingerprint=d.get("signer_fingerprint", ""),
        )


def compute_index_digest(data: dict[str, Any]) -> str:
    """Compute SHA-256 digest of discovery index data."""
    # Exclude signature and index_digest from the digest computation
    payload = {k: v for k, v in data.items() if k not in ("signature", "index_digest")}
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode()).hexdigest()


# ── Discovery Index Receipt ──────────────────────────────────────────────────

@dataclass
class DiscoveryIndexReceipt:
    """Receipt for a fetched and verified discovery index."""
    index_id: str
    source_url: str
    index_digest: str
    fetched_at: str
    signer_fingerprint: str = ""
    signature_present: bool = False
    signature_verified: bool = False
    verifier_key_digest: str = ""
    registry_count: int = 0
    publisher_count: int = 0
    package_count: int = 0
    policy_profile_digest: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "index_id": self.index_id,
            "source_url": self.source_url,
            "index_digest": self.index_digest,
            "fetched_at": self.fetched_at,
            "signer_fingerprint": self.signer_fingerprint,
            "signature_present": self.signature_present,
            "signature_verified": self.signature_verified,
            "verifier_key_digest": self.verifier_key_digest,
            "registry_count": self.registry_count,
            "publisher_count": self.publisher_count,
            "package_count": self.package_count,
            "policy_profile_digest": self.policy_profile_digest,
        }


# ── Marketplace Registry Add Receipt ─────────────────────────────────────────

@dataclass
class MarketplaceRegistryAddReceipt:
    """Receipt for adding a registry from discovery to federation config."""
    registry_id: str
    base_url: str
    source_index_id: str
    source_url: str
    added_at: str
    policy_profile_digest: str = ""
    policy_approved: bool = False
    federation_config_digest: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "registry_id": self.registry_id,
            "base_url": self.base_url,
            "source_index_id": self.source_index_id,
            "source_url": self.source_url,
            "added_at": self.added_at,
            "policy_profile_digest": self.policy_profile_digest,
            "policy_approved": self.policy_approved,
            "federation_config_digest": self.federation_config_digest,
        }


# ── Discovery Fetcher ────────────────────────────────────────────────────────

def fetch_discovery_index(
    source_url: str,
    fetcher_fn: Any | None = None,
    max_size: int = MAX_INDEX_SIZE_BYTES,
) -> PublicDiscoveryIndex:
    """Fetch and validate a discovery index from a source URL.

    Args:
        source_url: URL to fetch the index from.
        fetcher_fn: Callable(url) -> raw_bytes. If None, uses urllib.
        max_size: Maximum allowed index size in bytes.

    Returns:
        PublicDiscoveryIndex with verified digest.

    Raises:
        DiscoveryError: If index is corrupt, stale, oversized, or invalid.
    """
    # Fetch raw data
    if fetcher_fn:
        raw = fetcher_fn(source_url)
    else:
        import urllib.request
        try:
            with urllib.request.urlopen(source_url, timeout=10) as resp:
                raw = resp.read()
        except Exception as e:
            raise DiscoveryError(f"Failed to fetch discovery index from {source_url}: {e}") from e

    # Size check
    if len(raw) > max_size:
        raise DiscoveryError(
            f"Discovery index oversized: {len(raw)} bytes > {max_size} bytes limit"
        )

    # Parse JSON
    try:
        data = json.loads(raw)
    except (json.JSONDecodeError, ValueError) as e:
        raise DiscoveryError(f"Discovery index is not valid JSON: {e}") from e

    if not isinstance(data, dict):
        raise DiscoveryError("Discovery index is not a JSON object")

    return parse_discovery_index(data, source_url)


def parse_discovery_index(
    data: dict[str, Any],
    source_url: str = "",
) -> PublicDiscoveryIndex:
    """Parse and validate a discovery index from raw data.

    Verifies:
    - Required fields present
    - Digest matches content
    - Registry count within limits
    - Package count within limits
    """
    if "index_id" not in data:
        raise DiscoveryError("Discovery index missing 'index_id'")
    if "generated_at" not in data:
        raise DiscoveryError("Discovery index missing 'generated_at'")

    # Verify digest
    expected_digest = compute_index_digest(data)
    stored_digest = data.get("index_digest", "")
    if stored_digest and stored_digest != expected_digest:
        raise DiscoveryError(
            f"Discovery index digest mismatch: stored {stored_digest[:16]}... "
            f"but recomputed {expected_digest[:16]}..."
        )

    # Build index
    index = PublicDiscoveryIndex.from_dict(data)
    index.source_url = source_url or data.get("source_url", "")
    index.index_digest = expected_digest  # always use computed digest

    # Check limits
    if len(index.registries) > MAX_REGISTRIES_PER_INDEX:
        raise DiscoveryError(
            f"Too many registries in index: {len(index.registries)} > {MAX_REGISTRIES_PER_INDEX}"
        )
    if len(index.packages) > MAX_PACKAGES_PER_INDEX:
        raise DiscoveryError(
            f"Too many packages in index: {len(index.packages)} > {MAX_PACKAGES_PER_INDEX}"
        )

    return index


# ── Discovery Policy Checks ──────────────────────────────────────────────────

def verify_discovery_signature(
    index: PublicDiscoveryIndex,
    public_key_pem: str | None = None,
) -> tuple[bool, str]:
    """Cryptographically verify a discovery index signature.

    v2.7.1: Field-present check is NOT sufficient.
    When a public key is provided, the signature is verified
    cryptographically using RSA-PSS-SHA256.

    Returns (valid, reason).
    """
    if not index.signature:
        return False, "Index has no signature"
    if not index.signer_fingerprint:
        return False, "Index has no signer fingerprint"

    if public_key_pem is None:
        # Without a public key, we can only confirm fields are present
        return True, "Signature fields present (no cryptographic verification without public key)"

    try:
        from cryptography.hazmat.primitives import hashes, serialization
        from cryptography.hazmat.primitives.asymmetric import padding

        public_key = serialization.load_pem_public_key(public_key_pem.encode())

        # Compute the payload that was signed
        payload_data = {k: v for k, v in index.to_dict().items()
                        if k not in ("signature", "index_digest")}
        canonical = json.dumps(payload_data, sort_keys=True, separators=(",", ":"))

        public_key.verify(
            bytes.fromhex(index.signature),
            canonical.encode(),
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=padding.PSS.MAX_LENGTH,
            ),
            hashes.SHA256(),
        )
        return True, "Signature cryptographically verified"
    except Exception as e:
        return False, f"Signature verification failed: {e}"


class DiscoverySignerResolver:
    """Maps signer fingerprints to public key PEMs.

    v2.7.2: Strict profiles require cryptographic verification.
    This resolver provides the public key for a given signer fingerprint.
    """

    def __init__(self) -> None:
        self._keys: dict[str, str] = {}  # fingerprint -> public_key_pem

    def add_signer(self, fingerprint: str, public_key_pem: str) -> None:
        """Register a trusted discovery signer."""
        self._keys[fingerprint] = public_key_pem

    def resolve(self, fingerprint: str) -> str | None:
        """Resolve a signer fingerprint to a public key PEM."""
        return self._keys.get(fingerprint)

    @property
    def known_fingerprints(self) -> list[str]:
        return list(self._keys.keys())


def check_discovery_policy(
    index: PublicDiscoveryIndex,
    org_profile: Any | None,
    signer_resolver: DiscoverySignerResolver | None = None,
) -> tuple[bool, str]:
    """Check if a discovery index is allowed by organization policy.

    v2.7.2: When require_discovery_signature_verification=True,
    the policy demands cryptographic verification, not field presence.
    The signer_resolver must provide the public key for the index's
    signer_fingerprint.

    Returns (allowed, reason).
    """
    if org_profile is None:
        return True, ""  # no profile = no restrictions on discovery itself

    # Check if discovery is allowed
    if not getattr(org_profile, "allow_public_discovery", True):
        return False, "Public discovery is disabled by active organization profile"

    # Check allowed sources
    allowed_sources = getattr(org_profile, "allowed_discovery_sources", [])
    if allowed_sources and index.source_url not in allowed_sources:
        return False, f"Discovery source '{index.source_url}' not in allowed sources"

    # Check signed index requirement
    require_signed = getattr(org_profile, "require_signed_discovery_index", False)
    require_crypto = getattr(org_profile, "require_discovery_signature_verification", False)
    trusted_signers = getattr(org_profile, "trusted_discovery_signers", [])

    if require_signed or require_crypto:
        if not index.signature:
            return False, "Profile requires signed discovery index but index is unsigned"
        if not index.signer_fingerprint:
            return False, "Profile requires signed discovery index but signer is unknown"

    # v2.7.3: Cryptographic verification when required
    if require_crypto:
        allow_any = getattr(org_profile, "allow_any_resolver_discovery_signer", False)

        if not allow_any:
            # v2.7.3: Empty trusted_discovery_signers fails closed.
            # The allowlist is not optional when crypto verification is required.
            if not trusted_signers:
                return False, (
                    "Profile requires cryptographic signature verification "
                    "but trusted_discovery_signers is empty — "
                    "strict profiles must define an explicit signer allowlist "
                    "or set allow_any_resolver_discovery_signer=True"
                )
            # Signer must be in the explicit allowlist
            if index.signer_fingerprint not in trusted_signers:
                return False, (
                    f"Discovery index signer '{index.signer_fingerprint}' "
                    "is not in trusted_discovery_signers"
                )

        # Need a resolver to get the public key
        if signer_resolver is None:
            return False, (
                "Profile requires cryptographic signature verification "
                "but no signer resolver was provided"
            )

        public_key_pem = signer_resolver.resolve(index.signer_fingerprint)
        if public_key_pem is None:
            return False, (
                f"Discovery index signer '{index.signer_fingerprint}' "
                "is not known to the signer resolver"
            )

        # Full cryptographic verification
        sig_valid, sig_reason = verify_discovery_signature(index, public_key_pem=public_key_pem)
        if not sig_valid:
            return False, f"Discovery index signature cryptographically invalid: {sig_reason}"

    elif require_signed:
        # v2.7.1 fallback: field presence check when crypto not required
        sig_valid, sig_reason = verify_discovery_signature(index)
        if not sig_valid:
            return False, f"Discovery index signature invalid: {sig_reason}"

    # Check index age
    max_age_days = getattr(org_profile, "maximum_discovery_index_age", 0)
    if max_age_days > 0 and index.generated_at:
        try:
            gen_time = datetime.fromisoformat(index.generated_at.replace("Z", "+00:00"))
            age = datetime.now(timezone.utc) - gen_time
            if age.days > max_age_days:
                return False, f"Discovery index is {age.days} days old (max {max_age_days})"
        except (ValueError, TypeError):
            return False, f"Discovery index has invalid generated_at timestamp"

    return True, ""


def check_registry_add_policy(
    listing: MarketplaceRegistryListing,
    org_profile: Any | None,
) -> tuple[bool, str]:
    """Check if a registry can be added from discovery.

    Returns (allowed, reason).
    """
    if org_profile is None:
        return True, ""

    if not getattr(org_profile, "allow_marketplace_registry_add", True):
        return False, "Marketplace registry add is disabled by active organization profile"

    # Registry must still pass remote registry policy
    if not getattr(org_profile, "allow_remote_registry", True):
        return False, "Remote registry is disabled by active organization profile"

    return True, ""


# ── Discovery Search ─────────────────────────────────────────────────────────

@dataclass
class SearchResult:
    """A search result from discovery."""
    registry_id: str
    base_url: str
    display_name: str
    description: str
    categories: list[str]
    matched_packages: list[str] = field(default_factory=list)
    reputation_hint: str = ""
    source_index_id: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "registry_id": self.registry_id,
            "base_url": self.base_url,
            "display_name": self.display_name,
            "description": self.description,
            "categories": self.categories,
            "matched_packages": self.matched_packages,
            "reputation_hint": self.reputation_hint,
            "source_index_id": self.source_index_id,
        }


def search_discovery_index(
    index: PublicDiscoveryIndex,
    query: str = "",
    category: str = "",
    package: str = "",
) -> list[SearchResult]:
    """Search a discovery index for registries matching criteria.

    Package claims are treated as informational only.
    """
    results: list[SearchResult] = []
    query_lower = query.lower()

    for reg in index.registries:
        # Query match
        if query_lower:
            searchable = f"{reg.display_name} {reg.description} {' '.join(reg.categories)}".lower()
            if query_lower not in searchable:
                continue

        # Category match
        if category and category not in reg.categories:
            continue

        # Package match
        matched_packages: list[str] = []
        if package:
            matched_packages = [p for p in reg.claimed_packages if package.lower() in p.lower()]
            if not matched_packages:
                continue

        results.append(SearchResult(
            registry_id=reg.registry_id,
            base_url=reg.base_url,
            display_name=reg.display_name,
            description=reg.description,
            categories=reg.categories,
            matched_packages=matched_packages,
            reputation_hint=reg.reputation_hint,
            source_index_id=index.index_id,
        ))

    return results


# ── Add Registry From Discovery ──────────────────────────────────────────────

def add_registry_from_discovery(
    listing: MarketplaceRegistryListing,
    index: PublicDiscoveryIndex,
    federation_store: Any,
    org_profile: Any | None = None,
) -> MarketplaceRegistryAddReceipt:
    """Add a discovered registry to federation config.

    NON-NEGOTIABLE: The registry is added as a normal FederatedRegistryConfig
    entry. No special trust. No auto-enable. Disabled by default until approved.

    Returns MarketplaceRegistryAddReceipt.
    """
    # Policy check
    allowed, reason = check_registry_add_policy(listing, org_profile)
    if not allowed:
        raise MarketplacePolicyDenial(reason)

    # Convert to federation config
    config = listing.to_federation_config()

    # Add to federation store
    federation_store.add(config)

    # Build receipt
    receipt = MarketplaceRegistryAddReceipt(
        registry_id=listing.registry_id,
        base_url=listing.base_url,
        source_index_id=index.index_id,
        source_url=index.source_url,
        added_at=datetime.now(timezone.utc).isoformat(),
        policy_approved=True,
    )

    if org_profile:
        receipt.policy_profile_digest = org_profile.compute_digest()

    receipt.federation_config_digest = federation_store.compute_digest()

    return receipt


# ── Verification ─────────────────────────────────────────────────────────────

@dataclass
class DiscoveryVerifyResult:
    """Result of verifying a discovery index."""
    valid: bool
    issues: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "valid": self.valid,
            "issues": self.issues,
        }


def verify_discovery_index(index: PublicDiscoveryIndex) -> DiscoveryVerifyResult:
    """Verify a discovery index's integrity.

    Checks:
    1. Index has required fields
    2. Digest matches content
    3. Registry count within limits
    4. All registries have valid base_url
    5. No duplicate registry IDs
    """
    issues: list[str] = []

    if not index.index_id:
        issues.append("Missing index_id")
    if not index.generated_at:
        issues.append("Missing generated_at")
    if not index.index_digest:
        issues.append("Missing index_digest")

    # Check registries
    seen_ids: set[str] = set()
    for reg in index.registries:
        if reg.registry_id in seen_ids:
            issues.append(f"Duplicate registry_id: {reg.registry_id}")
        seen_ids.add(reg.registry_id)

        if not reg.base_url.startswith(("http://", "https://")):
            issues.append(f"Registry '{reg.registry_id}' has invalid base_url: {reg.base_url}")

    # Check limit
    if len(index.registries) > MAX_REGISTRIES_PER_INDEX:
        issues.append(f"Too many registries: {len(index.registries)}")

    return DiscoveryVerifyResult(valid=len(issues) == 0, issues=issues)


# ── Discovery Store ──────────────────────────────────────────────────────────

@dataclass
class DiscoveryStoreEntry:
    """A cached discovery index entry."""
    index: PublicDiscoveryIndex
    fetched_at: str
    receipt: DiscoveryIndexReceipt | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "index": self.index.to_dict(),
            "fetched_at": self.fetched_at,
            "receipt": self.receipt.to_dict() if self.receipt else None,
        }


class DiscoveryStore:
    """File-backed store for cached discovery indices."""

    def __init__(self, entries: dict[str, DiscoveryStoreEntry] | None = None):
        self._entries: dict[str, DiscoveryStoreEntry] = entries or {}

    def get(self, index_id: str) -> DiscoveryStoreEntry | None:
        return self._entries.get(index_id)

    def set(self, entry: DiscoveryStoreEntry) -> None:
        self._entries[entry.index.index_id] = entry

    @property
    def all_entries(self) -> list[DiscoveryStoreEntry]:
        return list(self._entries.values())

    def to_dict(self) -> dict[str, Any]:
        return {
            "version": DISCOVERY_VERSION,
            "entries": {k: v.to_dict() for k, v in self._entries.items()},
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> DiscoveryStore:
        entries = {}
        for k, v in d.get("entries", {}).items():
            idx = PublicDiscoveryIndex.from_dict(v["index"])
            receipt_data = v.get("receipt")
            receipt = DiscoveryIndexReceipt(**receipt_data) if receipt_data else None
            entries[k] = DiscoveryStoreEntry(
                index=idx,
                fetched_at=v.get("fetched_at", ""),
                receipt=receipt,
            )
        return cls(entries=entries)


def get_discovery_store_path() -> str:
    return os.environ.get(
        "NODECHAIN_DISCOVERY_STORE",
        os.path.join("data", "discovery_store.json"),
    )


def load_discovery_store(path: str | None = None) -> DiscoveryStore:
    """Load discovery store. Raises DiscoveryError if corrupt."""
    path = path or get_discovery_store_path()
    p = Path(path)
    if not p.exists():
        return DiscoveryStore()
    raw = p.read_text(encoding="utf-8")
    try:
        data = json.loads(raw)
    except (json.JSONDecodeError, ValueError) as e:
        raise DiscoveryError(f"Discovery store corrupt at {path}: {e}") from e
    if not isinstance(data, dict):
        raise DiscoveryError(f"Discovery store at {path} is not a valid JSON object")
    return DiscoveryStore.from_dict(data)


def save_discovery_store(store: DiscoveryStore, path: str | None = None) -> str:
    """Save discovery store atomically."""
    path = path or get_discovery_store_path()
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(".tmp")
    tmp.write_text(json.dumps(store.to_dict(), indent=2, sort_keys=True), encoding="utf-8")
    tmp.replace(p)
    return str(path)
